version: '3.0'
services:
  php:
    build: .
    container_name: phpapp
    env_file:
      - .env
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./deploy/local.ini:/usr/local/etc/php/local.ini
    expose:
      - 9000
    depends_on:
      - redis
      - mysql
    networks:
      - app-network
  mysql:
    container_name: mysql
    image: mariadb
    volumes:
      - mysql:/var/lib/mysql/
    environment:
        MYSQL_DATABASE: toranjlaravel2
        MYSQL_ROOT_PASSWORD: 123789
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - app-network
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379

    networks:
      - app-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app-network
volumes:
  mysql:

networks:
  app-network:
      driver: bridge

